### PR TITLE
[BCEngine] MCMC[User]Initialize() throws exceptions

### LINKED ISSUE #91: Segfault/ out of range exception when using MCMCUserInterface [Master Branch]
Dear developers,

I have found a bug in the BCEngineMCMC. If you use the MCMCUserInterface you have access to the function MCMCx(int chain), which returns the current values of all parameters. In case the MCMCInititialze() fails the fMCMCx vector is cleared, which lead to an  out_of_range exception if you access it via the MCMCx(int chain) method. If the interface code is needed I can provide it via mail.
Regards

Thomas

### PR DESCRIPTION
**Pull request by fredRos**
Now errors can't be ignored anymore and the chain doesn't run, avoiding hard-to-find segfaults.

Resolves #91

### CODE REVIEW

**Comment by oschulz** [comment]
Can't merge yet because of conflicts.

**Comment by fredRos** [comment]
I fixed the conflicts

File: BAT/BCEngineMCMC.h [hunk 1]
```diff
@@ -1288,22 +1288,23 @@ class BCEngineMCMC
...
+     * chosen and before any call to user methods such as
+     * LogLikelihood() or LogAPrioriProbability() are
+     * issued. MCMCUserInitialize() is useful for example to allocate
+     * separate copies of objects within the user model, one per
+     * chain, for thread safety.
      *
-     * @return Success of action. */
-    virtual bool MCMCUserInitialize()
-    { return true; }
+     * @note Any error inside MCMCUserInitialize() should be signaled via an exception. */
```
Comment (oschulz) [inline BAT/BCEngineMCMC.h]: Nice!
